### ISSUE TITLE
Add composer.json and add module to packagist

### ISSUE THREAD

**Issue by seyfer** [michal-m/kohana-modules-devtools#1]
see example in my repos

**Comment by michal-m** [comment]
Hi seyfer,

I no longer have enough free time to develop this module. Feel free to fork it and carry on the development.

**Comment by seyfer** [comment]
@michal-m , thank you.

I will do this job. Please, give me your email, which I can write in credentials in composer authors.

**Comment by michal-m** [comment]
michal.j.musial@gmail.com

Thanks @seyfer!
